apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-deployment
  labels:
    app: cv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cv
  template:
    metadata:
      labels:
        app: cv
    spec:
      containers:
      - name: cv
        image: yathrebdifallah233/cvonepage:latest
        ports:
        - containerPort: 80
