apiVersion: v1
kind: Service
metadata:
  name: cv-service
spec:
  type: NodePort
  selector:
    app: cv
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30085  # port externe accessible depuis votre machine physique
