---
- name: Download terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.9.6/terraform_1.9.6_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes

- name: ensure executable
  file:
    path: /usr/local/bin/terraform
    mode: '0755'
